### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by eliottrosenberg** [NVIDIA/cuQuantum#118]
The webpage for the docker container appears to be down: [https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuquantum-appliance](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuquantum-appliance).

**Comment by mtjrider** [comment]
@eliottrosenberg thanks for posting. We're working on it.

cc @tlubowe

**Comment by mtjrider** [comment]
@eliottrosenberg 

Here's an update:

1. We're still working on the outage pertaining to the [landing page for cuQuantum Appliance on NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/cuquantum-appliance). We'll have more information posted tomorrow.
2. The images themselves remain anonymously pullable. See below for all of the latest tags.

Please note the existence of a new `-arm64` tag, targeting systems with the ARM architecture. 
If you have any additional comments, questions, or concerns, please let us know.

Here's an excerpt from the current _cuQuantum Appliance landing page on NGC_ under the `Important change notices` section:

----
## Important change notices

### version `== 23.10`

**The following image tags are available**:

```bash
nvcr.io/nvidia/cuquantum-appliance:23.10
nvcr.io/nvidia/cuquantum-appliance:23.10-devel-ubuntu22.04

nvcr.io/nvidia/cuquantum-appliance:23.10-arm64
nvcr.io/nvidia/cuquantum-appliance:23.10-devel-ubuntu22.04-arm64

nvcr.io/nvidia/cuquantum-appliance:23.10-devel-ubuntu20.04
```

Before v23.10, the operating system in the container was Ubuntu 20.04.
In v23.10, we added support for Ubuntu 22.04 without dropping support for Ubuntu 20.04.
To avoid breaking changes implied by altering the image tag, `nvcr.io/nvidia/cuquantum-appliance:23.10` now points to `nvcr.io/nvidia/cuquantum-appliance:23.10-devel-ubuntu22.04`.

This means that for a given machine architecture,`march='arm64'` or `march='x86_64'`, 
pulling from `cuquantum-appliance:23.10-${march}` is equivalent to pulling from `cuquantum-appliance:23.10-${march}`. The following two `docker pull` commands will download the same image.

**Comment by tlubowe** [comment]
@eliottrosenberg the issue should be resolved (some formatting changes are pending).
