### ISSUE TITLE
The output of apply_matrix_batched in cuQuantum Python is same as input

### ISSUE THREAD

**Issue by easonoob** [NVIDIA/cuQuantum#133]
This is a very cool library! I've just tried out this library using the batched_gate_application.py sample (without changing anything in the sample code) but I get `ValueError: does not match result`. When I checked the input and output state vectors, they are exactly the same. Then, I tried other functions including `apply_gate_matrix` and `compute_expectations_on_pauli_basis` but they are also the same, the output state vector is same as the input one. I've also tried reinstalling cuQuantum Python, reinstalling CUDA toolkit, and creating a new Conda environment but it all didn't work. Any helps will be appreciated, thanks!

**Comment by ymagchi** [comment]
Hi @easonoob,
Thank you for sharing this. 

Could you please confirm whether `compute_expectations_on_pauli_basis` itself returned expected values?
Also, it would be helpful for us if you could share your environment (by `nvidia-smi`).

**Comment by easonoob** [comment]
Hi @ymagchi, thank you for replying. The `compute_expectations_on_pauli_basis` returned the same as the input like other functions. I am using a GTX 1080 (maybe it is too old?).
`nvidia-smi`:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080         Off| 00000000:03:00.0  On |                  N/A |
| 38%   40C    P2               41W / 180W|    434MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by ymagchi** [comment]
Hi @easonoob,
Thank you for sharing the output.
GTX 1080 is based on Pascal architecture, which is not supported in cuQuantum SDK. NVIDIA GPU with Compute Capability >= 7.0 (e.g., Volta, Turing, Ampere, Ada, and Hopper) is required to obtain expected results.

**Comment by easonoob** [comment]
Ok, thanks for the information!
