### ISSUE TITLE
Support user defined seed in `cutensornetSamplerSample` and `sampler_sample`

### ISSUE THREAD

**Issue by PabloAndresCQ** [NVIDIA/cuQuantum#143]
There's a [note in the docs](https://docs.nvidia.com/cuda/cuquantum/latest/cutensornet/api/functions.html#cutensornetsamplersample) of `cutensornetSamplerSample`, indicating that currently there is no support for user-defined RNG seeds. This is an important feature for debugging purposes in quantum experiments. Will this be included in the next release?

**Comment by DmitryLyakh** [comment]
We are working on adding a custom random seed, please stay tuned.

**Comment by yangcal** [comment]
In the latest cuTensorNet v2.5.0, we have added new enum entry `CUTENSORNET_SAMPLER_CONFIG_DETERMINISTICE` under `cutensornetSamplerAttributes`. Please refer to the documentation [here](https://docs.nvidia.com/cuda/cuquantum/latest/cutensornet/api/types.html#_CPPv4N30cutensornetSamplerAttributes_t40CUTENSORNET_SAMPLER_CONFIG_DETERMINISTICE).

Meanwhile, we have released a python tensor network simulator with sampling capability under the experimental module and seed is supported in the `compute_sampling` method. Please check out our documentation [here](https://docs.nvidia.com/cuda/cuquantum/latest/python/api/generated/cuquantum.cutensornet.experimental.NetworkState.html#cuquantum.cutensornet.experimental.NetworkState.compute_sampling) and your feedback on our simulator APIs are more than welcome.
