### ISSUE TITLE
Changes of expression order of `CircuitToEinsum.amplitude` from v23 to v24 

### ISSUE THREAD

**Issue by chunyulin** [NVIDIA/cuQuantum#148]
Hi All, when attempting to port the tensor network QSVM code from v23 to v24, I noticed that the tensor expression order of `CircuitToEinsum.amplitude` has changed. In v23, the result expression iterates over qubit line first, then over layers; while in v24, it iterates over layers first (until double-qubit gate), then over the next of the last-visiting qubit lines. A preliminary benchmark shows that while the contraction performance remains similar, finding the optimal path takes almost twice as long in v24.

I'm curious about the design philosophy behind this change. Was it motivated by a specific use case? Many thanks for any insights.

**Comment by yangcal** [comment]
From a quick look at our implementation, I don't think we changed the order of expression from v23.xx to v24.xx. In [parse_inputs](https://github.com/NVIDIA/cuQuantum/blob/main/python/cuquantum/cutensornet/_internal/circuit_converter_utils.py#L98-L102) function, we always put tensors for the vacuum state first, followed by gate operands. Do you have any minimal reproducer?

**Comment by chunyulin** [comment]
After double-checking my code, I realized the changes were due to the input circuit, not the cuQuantum implementation.
Below is a minimal demonstration of the difference. 
Many thanks. 

```
import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit.circuit import ParameterVector
from qiskit_machine_learning.kernels import QuantumKernel
from cuquantum import CircuitToEinsum

def make_qc(nq):
    param = ParameterVector("p",nq)
    qc = QuantumCircuit(nq)
    qc.h(list(range(nq)))
    for q in range(nq):
        qc.ry(param.params[q],[q])
    for q in range(nq-1):
        qc.cx(q, q+1)
    return qc

NQ = 2
vec = np.ones(NQ)
psix = make_qc(NQ)
qk = QuantumKernel(feature_map=psix)
circuit = qk.construct_circuit(vec,vec,False)
exp, _ = CircuitToEinsum(circuit, dtype='complex128', backend='cupy').amplitude(  str(0).zfill(NQ) )
print(exp)    ### a,b,ca,db,ec,fd,ghfe,ijgh,ki,lj,mk,nl,n,m->
exp, _ = CircuitToEinsum(circuit.decompose(), dtype='complex128', backend='cupy').amplitude(  str(0).zfill(NQ) )
print(exp)    ### a,b,ca,dc,eb,fe,ghfd,ijgh,kj,lk,mi,nm,l,n->
```
