### ISSUE TITLE
[Question] Why are Z-basis outcomes restricted to all-zero and all-one?

### ISSUE THREAD

**Issue by TysonRayJones** [NVIDIA/cuQuantum#163]
> I have extensively edited this question since its original framing

The function [`custatevecCollapseOnZBasis`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html#custateveccollapseonzbasis) has signature
```C++
custatevecStatus_t custatevecCollapseOnZBasis(
    custatevecHandle_t handle, 
    void *sv, 
    cudaDataType_t svDataType, 
    const uint32_t nIndexBits, 
    const int32_t parity, 
    const int32_t *basisBits, 
    const uint32_t nBasisBits, 
    double norm
)
```
which permits specifying an arbitrary number (`nBasisBits`) of "target qubits" (`basisBits`), of which there are `1 << nBasisBits` unique possible outcomes. Alas, the boolean argument `"parity – [in] parity, 0 or 1"` constrains us to collapsing to only **_two_** of these possible outcomes. I assume these are the all-zero and all-one outcomes.

This is an unusual limitation. A three-qubit Z-measurement upon an arbitrary state, for example, could yield any of the eight outcomes:
```
000, 001, 010, 011, 100, 101, 110, 111
```
yet the `custatevecCollapseOnZBasis` interface permits collapsing only to `000` and `111`.

Fortunately, we can work around this limitation and collapse to arbitrary Z-basis states like `101`, by invoking `custatevecCollapseOnZBasis` _twice_. We partition `basisBits` into the indices corresponding to `0` and `1` outcomes, and collapse to an all-zero and all-one state in-turn, using `sqrt(norm)`. This works because all the amplitudes erroneously scaled by the first invocation will be zero'd by the next. I use this trick [here](https://github.com/QuEST-Kit/QuEST/blob/2d930cef1dbc210ee7972d054f69489c903c45b3/quest/src/gpu/gpu_subroutines.cpp#L1441) to call `custatevecCollapseOnZBasis` like [this](https://github.com/QuEST-Kit/QuEST/blob/2d930cef1dbc210ee7972d054f69489c903c45b3/quest/src/gpu/gpu_cuquantum.cuh#L337). 

Alas, such a workaround is not possible for  [`custatevecAbs2SumOnZBasis`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html#custatevecabs2sumonzbasis), which has signature
```C++
custatevecStatus_t custatevecAbs2SumOnZBasis(
    custatevecHandle_t handle, 
    const void *sv, 
    cudaDataType_t svDataType, 
    const uint32_t nIndexBits, 
    double *abs2sum0, 
    double *abs2sum1, 
    const int32_t *basisBits, 
    const uint32_t nBasisBits
)
```
There again, despite specifying `nBasisBits` qubits with `1 << nBasisBits` unique outcomes, we are only able to compute the probability (the abs sum) of _two_ outcomes; all-zero and all-one (obtained as `abs2sum0` and `abs2sum1`).

We cannot simply invoke `custatevecAbs2SumOnZBasis` twice like we did for `custatevecCollapseOnZBasis`. Due to quantum correlations, the probability of a basis state like `00011` is _not_ necessarily the product of probabilities `000` and `11`. We would instead have to leverage [conditional probability](https://en.wikipedia.org/wiki/Conditional_probability), whereby
```
P(00111) = P(111) P(00 | 111)
``` 
and so compute `P(111)` using `custatevecAbs2SumOnZBasis`, then collapse to `111` via `custatevecCollapseOnZBasis` before measuring `P(00)` with `custatevecAbs2SumOnZBasis` (which would effectively compute `P(00 | 111)`). This requires modifying the state!

So: is there a better way to use cuStateVec to perform arbitrary Z-basis measurements/projections/probability-calculations?

**Comment by TysonRayJones** [comment]
Another issue to note; the type `int32_t` of `parity` is of insufficient precision to specify the outcome when `nBasisBits > 32`.

**Comment by ymagchi** [comment]
Hi @TysonRayJones ,

`custatevecCollapseOnZBasis` collapses the state vector on a given parity.
In the above example with a 3-qubit state vector,
`000`, `011`, `101`, `110` have parity 0 while `001`, `010`, `100`, `111` have parity 1. `custatevecAbs2SumOnZBasis` and `custatevecMeasureOnZBasis` will group state vector elements by parity as well.

We also provide API set for multiple qubit measurement by `custatevecAbs2SumArray`, `custatevecCollapseByBitString`, and `custatevecBatchMeasure`. These functions will compute a probability array and collapse state vector elements based on `1 << nBasisBits` unique possible outcomes; thus, I think they will be more appropriate for your use case.

**Comment by TysonRayJones** [comment]
Hi @ymagchi ,

Ah beat me to it as I was typing a response! Indeed I just found (d'oh) [`custatevecCollapseByBitString`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html#custateveccollapsebybitstring) which collapses to an arbitrary Z-basis state, and [`custatevecAbs2SumArray`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html#custatevecabs2sumarray) which calculates the probabilities of _all_ basis-states of the specified sub-register.

Alas this still leaves me with a confusion: how can I compute the probability of a particular Z-basis outcome _without_ computing the probabilities of _all_ outcomes? For example, consider I wish to find the probability of a `20`-qubit substate in a `30`-qubit statevector. We know only `2^(30-20) = 2^10` amplitudes need to be reduced, but using `custatevecAbs2SumArray` would involve repeating this reduction to find `2^20 - 1` superfluous probabilities! Is there a way to compute only _one_ probability?

**Comment by ymagchi** [comment]
> how can I compute the probability of a particular Z-basis outcome without computing the probabilities of all outcomes? For example, consider I wish to find the probability of a 20-qubit substate in a 30-qubit statevector. We know only 2^(30-20) = 2^10 amplitudes need to be reduced, but using custatevecAbs2SumArray would involve repeating this reduction to find 2^20 - 1 superfluous probabilities! Is there a way to compute only one probability?

For this case, `maskBitString`, `maskOrdering`, and `maskLen` in the measurement API will be available to set a bit mask in the state vector index. When these parameters are provided, the computations are performed only for partial state vector elements whose indices match the input mask bit string, which enables to compute just 1 element of the entire probability array.

**Comment by TysonRayJones** [comment]
Hmm, but the doc for [`custatevecAbs2SumArray`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html?highlight=bitordering#custatevecabs2sumarray) includes:
> By definition, bit positions in `bitOrdering` and `maskOrdering` arguments **should not overlap**.

Wouldn't we require them to overlap? Furthermore, what index of array `abs2sum` would be written to? We should wish it to be the first so we do not have to construct a large array, but we may wish to obtain the `n`-th state among `bitOrdering`, where `n >> 1`. For example, the all-one state at index `2^20 - 1`!

Is there an example of how to find the probability of a single sub-string (i.e. a "get probability" version of `custatevecCollapseByBitString`)?

**Comment by ymagchi** [comment]
When we specify bit value into each qubit in `custatevecAbs2SumArray`, its index will be moved from `bitOrdering` to `maskBitString`/`maskOrdering`.

For example, if we want to compute one probability for state vector elements whose indices are 1 for 0-19th index bits, the input parameters would be as follows.
```
int* bitOrdering = nullptr;
int bitOrderingLen = 0;

int maskBitString[] = {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
int maskOrdering[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
int maskLen = 20;
```

The size of the probability array obtained by `custatevecAbs2SumArray` is `2 ** bitOrderingLen` and index bits that are not specified in either `bitOrdering` or `maskOrdering` are folded (summed up) in the probability computation. In the above case, all the probabilities for 20th-29th index bits are accumulated into one scalar.

**Comment by TysonRayJones** [comment]
Wew that's a brilliant help, thanks very much!
