### ISSUE TITLE
`custatevecApplyMatrix` execute on the default CUDA stream？

### ISSUE THREAD

**Issue by fxfxfxfxfxfxfxfx** [NVIDIA/cuQuantum#168]
In `custatevec`, is `custatevecApplyMatrix` executed on the default CUDA stream? I want to make `custatevecApplyMatrix` and `cudaMemcpy` run simultaneously, but it seems to fail.

**Comment by yangcal** [comment]
Hello, 

We have [`custatevecSetStream`](https://docs.nvidia.com/cuda/cuquantum/latest/custatevec/api/functions.html#custatevecsetstream) API to allow users to set the stream for cuStateVec library to execute its routines. Note that user is responsible for establishing proper stream order in asynchronous execution.

**Comment by fxfxfxfxfxfxfxfx** [comment]
Thank you very much for your response. I apologize for not reading the document carefully. Best regards. ^_^
