### ISSUE TITLE
How to run a browser for jupyter notebook in cuQuantum docker environment ?

### ISSUE THREAD

**Issue by ShashiQubit** [NVIDIA/cuQuantum#18]
![Nvidia cuQuantum](https://user-images.githubusercontent.com/87139518/192094539-18a2addd-4119-47e2-9fec-b8750ea7edbe.png)
Following the well designed documentation I was able to successfully get this to run. I am using terminal to write my Quantum experiments.I want to know how to run a jupyter notebook inside docker container. After installing jupyter in docker  and running it gives a link that doesn't open in a browser of my linux system.I then installed firefox inside cuQuantum docker but it doesn't launch the browser. Gives a display not found error.How can I run my experiments in jupyter ?

**Comment by mtjrider** [comment]
> After installing jupyter in docker  and running it gives a link that doesn't open in a browser of my linux system. I then installed firefox inside cuQuantum docker but it doesn't launch the browser. Gives a display not found error.How can I run my experiments in jupyter ?  

Typically, you launch the Docker container and then run Jupyter server inside the container and access it from the host machine via browser outside of the container.

To do this, you'll need to publish the appropriate port in the container to the host operating systems. Something like this:

```
docker run -p 8888:8888 ...
```

Then on the host OS, open a browser and navigate to `localhost:8888`

There's also a tool called "Jupyter Docker Stacks" that may be relevant.

**Comment by ShashiQubit** [comment]
@mtjrider running using the "Jupyter Docker Stacks" method doesn't take into account the cuQuantum docker environment. Meaning in notebook I can't import cuquantum or cirq.
There is something I am missing and I don't know what.
Here is how I am running the command in terminal.
`$ docker run --gpus all --rm nvcr.io/nvidia/cuquantum-appliance:22.07-cirq`
and then running
`$ docker run -p 8888:8888 jupyter/scipy-notebook:0fd03d9356de`
It launches the notebook but the libraries can't be imported.

**Comment by ShashiQubit** [comment]
Issue solved !
To run experiments in jupyter I had to execute the following commands:
`$ docker run --gpus all -it --rm -v "/home/shashi":"/workspace" -p 80:8888 nvcr.io/nvidia/cuquantum-appliance:22.07-cirq /bin/bash`
And then when inside the container I had to install jupyterlab using:
`pip3 install jupyterlab`
And to launch the nootbook :
`jupyter lab --ip 0.0.0.0 --port 8888 --allow-root`
Now in the next step when copy and pasting the link in browser I had to change the port from 888 to 80
ex: `http://127.0.0.1:8888/lab?token=....` to `http://127.0.0.1:80/lab?token=....`

@mtjrider  Thanks ! for the `docker run -p 8888:8888 ...` clue
