### ISSUE TITLE
Build issues with top-level cutensornet.h symlink

### ISSUE THREAD

**Issue by 1tnguyen** [NVIDIA/cuQuantum#47]
When installing the latest version of `cuquantum` via `apt-get`, `/usr/include/cutensornet.h` is a symlink to `/usr/include/libcuquantum/12/cutensornet.h` (I'm using CUDA12).

However, this header file refers to `<cutensornet/types.h>` in `cutensornet` sub-directory, which is **not** symlinked to `/usr/include/`. This would create some difficulties in setting up CMake whereby it will fail to build if `/usr/include/` is detected as the `cutensornet` include directory, for example.

**Comment by leofang** [comment]
Thanks, Thien, for reporting. Created an internal ticket CUDAINST-2317.

**Comment by leofang** [comment]
Hi @1tnguyen, the internal team has fixed this issue, I can see that the symlinks exist now
```
# ls -l /usr/include/cu*
lrwxrwxrwx 1 root root 30 Apr 25 19:48 /usr/include/custatevec.h -> /etc/alternatives/custatevec.h
lrwxrwxrwx 1 root root 29 Apr 25 19:48 /usr/include/cutensornet -> /etc/alternatives/cutensornet
lrwxrwxrwx 1 root root 31 Apr 25 19:48 /usr/include/cutensornet.h -> /etc/alternatives/cutensornet.h
```
Would you be able to confirm for me before I close this issue? Thanks!

**Comment by 1tnguyen** [comment]
Hi @leofang 

I've just tried to install `cuquantum` again, but  `/usr/include/cutensornet` is still only a symlink to the `cutensornet.h` **file**, not the sub-directory.

e.g., the symlinks in `/etc/alternatives/` show that `/etc/alternatives/cutensornet -> /usr/include/libcuquantum/12/cutensornet.h`

```
root@fe4733ecb669:/usr/include# ls -l /etc/alternatives/cu*
lrwxrwxrwx 1 root root 20 Mar  7 22:17 /etc/alternatives/cuda -> /usr/local/cuda-12.1
lrwxrwxrwx 1 root root 20 Apr 27 03:22 /etc/alternatives/cuda-11 -> /usr/local/cuda-11.8
lrwxrwxrwx 1 root root 20 Mar  7 22:17 /etc/alternatives/cuda-12 -> /usr/local/cuda-12.1
lrwxrwxrwx 1 root root 36 Mar  7 22:21 /etc/alternatives/cufile.json -> /usr/local/cuda-12.1/gds/cufile.json
lrwxrwxrwx 1 root root 47 Apr 27 03:22 /etc/alternatives/cuquantum -> /usr/src/libcuquantum/12/distributed_interfaces
lrwxrwxrwx 1 root root 41 Apr 27 03:22 /etc/alternatives/custatevec.h -> /usr/include/libcuquantum/12/custatevec.h
lrwxrwxrwx 1 root root 42 Apr 27 03:22 /etc/alternatives/cutensornet -> /usr/include/libcuquantum/12/cutensornet.h
lrwxrwxrwx 1 root root 42 Apr 27 03:22 /etc/alternatives/cutensornet.h -> /usr/include/libcuquantum/12/cutensornet.h

```
Here is the full package information, just to make sure I got the update:

```
root@fe4733ecb669:/usr/include# apt show -a cuquantum-dev
Package: cuquantum-dev
Version: 23.03.0.20-1
Priority: optional
Section: multiverse/devel
Source: cuquantum
Maintainer: cudatools <cudatools@nvidia.com>
Installed-Size: 18.4 kB
Depends: libcuquantum0-dev-cuda-11 (>= 23.03.0.20), libcuquantum0-dev-cuda-12 (>= 23.03.0.20), libcuquantum0-static-cuda-11 (>= 23.03.0.20), libcuquantum0-static-cuda-12 (>= 23.03.0.20)
Breaks: cuquantum-dev (<< 23.03.0.20-1)
Replaces: cuquantum-dev (<< 23.03.0.20-1)
Download-Size: 7052 B
```

**Comment by DmitryLyakh** [comment]
Hi Thien,
Would you consider uninstalling cuquantum and reinstalling it from the tarball instead? That way you will have all include and library files in the same location, and you can make any necessary symlinks yourself (for example, symlinks inside the lib subdirectory that would point to the right CUDA version, 11 or 12).

**Comment by 1tnguyen** [comment]
Hi @DmitryLyakh,

Absolutely, I can. I've had a similar workaround to use the header files from `/usr/include/libcuquantum/12/` rather than the symlinks in `/usr/include`.

Just out of curiosity, the symlink of `/usr/include/cutensornet` (no file extension) to the header file `/usr/include/libcuquantum/12/cutensornet.h` rather than the `cutensornet` sub-directory: is it a feature or a bug :-)?

**Comment by leofang** [comment]
Thanks again for working with us @1tnguyen. We've made the Linux packages better in the latest 23.06 release. In particular, we now support `update-alternatives` to select the package that supports the target CUDA version (11 or 12). So such manual maneuver shouldn't be needed anymore (ex: I expect you can find `/usr/include/cutensornet.h`). Please kindly give it a shot and feel free to reopen if you encounter any issues!
