### ISSUE TITLE
pip module search for libcublas.so.11

### ISSUE THREAD

**Issue by sanori** [NVIDIA/cuQuantum#5]
Environment:
- Ubuntu 20.04 LTS
- Python 3.8

Symptom:
```
>>> import cuquantum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cuquantum/__init__.py", line 1, in <module>
    from cuquantum import custatevec
  File "/usr/local/lib/python3.8/dist-packages/cuquantum/custatevec/__init__.py", line 1, in <module>
    from cuquantum.custatevec.custatevec import *
ImportError: libcublas.so.11: cannot open shared object file: No such file or directory

```

I guess that pyculib should be converted to pip, too.

**Comment by leofang** [comment]
This is expected. cuQuantum Python depends on cuQuantum SDK, which in turn depends on cuBLAS both directly and indirectly. If you installed it via pip, please make sure the CUDA Toolkit (which includes libcublas.so) is installed and included in your LD_LIBRARY_PATH: 
https://docs.nvidia.com/cuda/cuquantum/python/README.html#install-cuquantum-python-from-source
(we will make this pointer clearer for our wheel users).

I am not sure what pyculib refers to. It's not used by this project or by any of our dependencies. Let us know if you have any further questions.

**Comment by sanori** [comment]
Thank you for prompt reply.
I found that libcublas.so.10 exist but libcublas.so.11 does not exist.
I guest I should upgrade nvidia-driver from 470 to upper version such as 510.

**Comment by sanori** [comment]
I was confused by the libraries provided by Ubuntu ppa.
I found that the CUDA version is not tightly related nVidia driver version.
And, I come to know I should install cupy with the same version of CUDA.

All the problems to install cuquantum with pip are solved.
Thanks.

**Comment by sanori** [comment]
FYI, I made a docker image to provide easy-to-try cuquantum-python sample codes in this repository.
- https://github.com/sanori/cuQuantum-docker

If this image or repository make problems, please let me know.
Thank you.

**Comment by leofang** [comment]
Hi @sanori yeah the NVIDIA CUDA graphics driver and the CUDA Toolkit need to be installed separately (but there are compatibility issues, ex: CUDA 11+ requires driver r450+). If you had `libcublas.so.10` it's likely you had CUDA 10.x installed, but cuQuantum requires CUDA 11 and indeed this requirement need to propagate to both CuPy and PyTorch (ex: you cannot install their CUDA 10.2-compatible wheels). 

Thanks for your interest in cuQuantum docker images. We offer an official docker image, available from NVIDIA NGC: 
https://docs.nvidia.com/cuda/cuquantum/appliance/index.html
It also includes a multi-GPU-enabled Cirq simulator in case you're a Cirq user.

**Comment by sanori** [comment]
@leofang Thank you for your information!!
It is great to use quantum simulator over nVidia by just pulling docker images.
```
python -c "import qsimcirq; print(qsimcirq.qsim_gpu)"
<module 'qsimcirq.qsim_cuda' from '/opt/conda/lib/python3.8/site-packages/qsimcirq/qsim_cuda.cpython-38-x86_64-linux-gnu.so'>
```

It works!!
