### ISSUE TITLE
docs: Inconsistent number for the default value of CUTENSORNET_CONTRACTION_OPTIMIZER_CONFIG_SLICER_SLICE_FACTOR

### ISSUE THREAD

**Issue by rht** [NVIDIA/cuQuantum#62]
https://docs.nvidia.com/cuda/cuquantum/cutensornet/overview.html#slicing says the default value is 32. But https://docs.nvidia.com/cuda/cuquantum/cutensornet/api/types.html#_CPPv4N49cutensornetContractionOptimizerConfigAttributes_t60CUTENSORNET_CONTRACTION_OPTIMIZER_CONFIG_SLICER_SLICE_FACTORE says the default value is 2.

**Comment by yangcal** [comment]
Hello, thanks for reporting. The current default one should be 32. We will update our docs soon.

**Comment by leofang** [comment]
This is fixed in the 23.06 docs. Thanks for letting us know, @rht!
https://docs.nvidia.com/cuda/cuquantum/latest/cutensornet/api/types.html#_CPPv4N49cutensornetContractionOptimizerConfigAttributes_t60CUTENSORNET_CONTRACTION_OPTIMIZER_CONFIG_SLICER_SLICE_FACTORE
