### ISSUE TITLE
Using cuQuantum Appliance 23.03 with Apptainer/Singularity

### ISSUE THREAD

**Issue by mtjrider** [NVIDIA/cuQuantum#76]
I see. I am using the cuquantum-appliance-23.03 and this is my workflow to recreate this issue:

```
$ apptainer pull docker://nvcr.io/nvidia/cuquantum-appliance:23.03
```
Then create a file `ghz.py` as in the documentation, run the container and execute the file
```
$ apptainer shell --nv -B $PWD cuquantum-appliance_23.03.sif
$ python ghz.py

Traceback (most recent call last):
  File "ghz.py", line 2, in <module>
    from cusvaer.backends import StatevectorSimulator
  File "/scratch/jookare/ghz.py", line 2, in <module>
    from cusvaer.backends import StatevectorSimulator
ModuleNotFoundError: No module named 'cusvaer.backends'; 'cusvaer' is not a package
```

_Originally posted by @Jookare in https://github.com/NVIDIA/cuQuantum/discussions/50#discussioncomment-6603064_

**Comment by mtjrider** [comment]
@jookare can you please try this?
```
$ apptainer shell --nv cuquantum-appliance_23.03.sif
...> which python
```
And then separately try this:
```
apptainer exec --nv cuquantum-appliance_23.03.sif which python
```

Please paste the output here.

**Comment by Jookare** [comment]
Thanks for creating a new issue for me. Here are the things you requested

```
[jookare@r17g05 cuQuantum]$ apptainer shell --nv cuquantum-appliance_23.03.sif
Apptainer> which python
Illegal option --
Usage: /usr/bin/which [-a] args
```

```
[jookare@r17g05 cuQuantum]$ apptainer exec --nv cuquantum-appliance_23.03.sif which python
/home/cuquantum/conda/envs/cuquantum-23.03/bin/python
```

**Comment by Jookare** [comment]
Still the same 
```
[jookare@r17g05 cuQuantum]$ apptainer run --nv cuquantum-appliance_23.03.sif
...tons of text...
Apptainer> which python
Illegal option --
Usage: /usr/bin/which [-a] args
```

**Comment by mtjrider** [comment]
@Jookare sorry it took me awhile to get back to this issue.

This call signature appears to be the only one that works:
`apptainer exec --nv cuquantum-appliance_23.03.sif ...`

The others aren't loading the appropriate runtime. Can you use this call signature for your application?

**Comment by mtjrider** [comment]
@Jookare let us know if this is still an issue.

**Comment by Jookare** [comment]
> @Jookare let us know if this is still an issue.

Hi sorry for the late reply! I was interning previously and as it ended so I do not have access to the HPC systems anymore and unfortunately can't test anymore

**Comment by mtjrider** [comment]
@Jookare I've closed this issue. If the issue resurfaces, or you have other questions, please feel free to reopen it or a create another issue.
