### ISSUE TITLE
CUTENSORNET_STATUS_CUTENSOR_VERSION_MISMATCH in line 198

### ISSUE THREAD

**Issue by davide-q** [NVIDIA/cuQuantum#8]
I am trying to compile the examples in the `/samples/cutensornet` directory and the compilation is successful, however it fails at runtime with the error in the subject.

According to https://github.com/NVIDIA/cuQuantum/blob/main/samples/cutensornet/README.md and https://docs.nvidia.com/cuda/cuquantum/cutensornet/index.html as of today, I must have

* [cuTensorNet v1.1.0](https://docs.nvidia.com/cuda/cuquantum/cutensornet/release_notes.html#cutensornet-v1-1-0)

* [CUDA Toolkit 11.x](https://developer.nvidia.com/cuda-downloads) and compatible driver r450+ (see [CUDA Driver Release Notes](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions)).

* [cuTENSOR v1.5.0 (or above)](https://developer.nvidia.com/cutensor)

I actually have

* cuTensorNet v1.1.0
* CUDA Version: 11.7 with Driver Version: 515.48.07
* cuTENSOR v1.6.0.3 (from libcutensor-linux-x86_64-1.6.0.3-archive)

So I meet all the requirements but still get that error. The only thing I can think is that libcutensor libraries are split in 3 directories for `10.2`, `11`, and `11.0` so perhaps CUDA v11.7 is too new? Does anybody has any insight?

**Comment by tlubowe** [comment]
Hi @davide-q thank you for reaching out. This is a known issue which will be patched in the 22.07.1 update we hope to be posting in the next few days. 

In the interim you can circumvent this error by downgrading cuTENSOR to a 1.5.x version. Please let us know how it goes.

**Comment by tlubowe** [comment]
Hi @davide-q I wanted to follow up to see if the above solved your issue or if you had any more updates for us? If not do you mind if I close this out?

**Comment by davide-q** [comment]
@tlubowe thanks for checking. I don't want to downgrade, so I am waiting for the update, has it been posted?

**Comment by tlubowe** [comment]
Hi @davide-q, 22.07.1 is currently going through our pipeline for QA, packaging and deployment. It is not posted yet. I will post back here when it is.

**Comment by leofang** [comment]
Hi @davide-q and all, v22.07.1 is out (#11), it'd be nice if you could give it a shot and let us know, thanks! 🙂

**Comment by davide-q** [comment]
Perfect, thanks so much. I will test it asap (=early next week) and report back.

**Comment by leofang** [comment]
Closing this issue as it's resolved in 22.07.1. @davide-q let us know if you still hit issues, thanks.

**Comment by davide-q** [comment]
As expected, this works fine. Thank so much for the very quick fix.

**Comment by tlubowe** [comment]
No problem at all! 

Thank you for being a user, and the issue report. Please don't hesitate to let us know if you ever run into anything else.
